<p style="font-family: Arial; font-size:3em;color:black;"> Session 5 - Lab Exercise 10</p>

In [1]:
# For this example, we will use K-Means Clustering Project database from Kaggle (https://www.kaggle.com/faressayah/k-means-clustering-private-vs-public-universities)
# We actually have the labels for this data set, but we will NOT use them for the KMeans clustering algorithm, since that is an unsupervised learning algorithm.
# As we will shortly see, we have a data frame with 777 observations on 18 variables.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline

In [2]:
df = pd.read_csv('College_Data',index_col=0)
df.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [3]:
df.head()

Private  Apps  Accept  Enroll  Top10perc  \
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  
Abilene Christian University       18.1           12    7041         60  
Adelphi University                 12.2           16   10527         56  
Adrian College                     12.9           30    8735         54  
Agnes Scott College                 7.7           37   19016         59  
Alaska Pacific University          11.9            2   10922         15

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 777 entries, Abilene Christian University to York College of Pennsylvania
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Private      777 non-null    object 
 1   Apps         777 non-null    int64  
 2   Accept       777 non-null    int64  
 3   Enroll       777 non-null    int64  
 4   Top10perc    777 non-null    int64  
 5   Top25perc    777 non-null    int64  
 6   F.Undergrad  777 non-null    int64  
 7   P.Undergrad  777 non-null    int64  
 8   Outstate     777 non-null    int64  
 9   Room.Board   777 non-null    int64  
 10  Books        777 non-null    int64  
 11  Personal     777 non-null    int64  
 12  PhD          777 non-null    int64  
 13  Terminal     777 non-null    int64  
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64  
 16  Expend       777 non-null    int64  
 17  Grad.Rate    777 non-null    int64  
dtypes: 

In [5]:
df.describe()

Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000   
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654   
std     3870.201484   2451.113971   929.176190   17.640364   19.804778   
min       81.000000     72.000000    35.000000    1.000000    9.000000   
25%      776.000000    604.000000   242.000000   15.000000   41.000000   
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000   
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000   
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000   

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000   
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952   
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360   
min      139.000000      1.000000   2340.000000  1780.000000    96.000000   
25%      992.000000     95.000000   7320.000000  3597.000000   470.000000   
50%     1707.000000    353.000000   9990.000000  4200.000000   500.000000   
75%     4005.000000    967.000000  12925.000000  5050.000000   600.000000   
max    31643.000000  21836.000000  21700.000000  8124.000000  2340.000000   

          Personal         PhD    Terminal   S.F.Ratio  perc.alumni  \
count   777.000000  777.000000  777.000000  777.000000   777.000000   
mean   1340.642214   72.660232   79.702703   14.089704    22.743887   
std     677.071454   16.328155   14.722359    3.958349    12.391801   
min     250.000000    8.000000   24.000000    2.500000     0.000000   
25%     850.000000   62.000000   71.000000   11.500000    13.000000   
50%    1200.000000   75.000000   82.000000   13.600000    21.000000   
75%    1700.000000   85.000000   92.000000   16.500000    31.000000   
max    6800.000000  103.000000  100.000000   39.800000    64.000000   

             Expend  Grad.Rate  
count    777.000000  777.00000  
mean    9660.171171   65.46332  
std     5221.768440   17.17771  
min     3186.000000   10.00000  
25%     6751.000000   53.00000  
50%     8377.000000   65.00000  
75%    10830.000000   78.00000  
max    56233.000000  118.00000

In [6]:
df[df['Grad.Rate']>100] # data cleaning

Private  Apps  Accept  Enroll  Top10perc  Top25perc  \
Cazenovia College     Yes  3847    3433     527          9         35   

                   F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  \
Cazenovia College         1010           12      9384        4840    600   

                   Personal  PhD  Terminal  S.F.Ratio  perc.alumni  Expend  \
Cazenovia College       500   22        47       14.3           20    7697   

                   Grad.Rate  
Cazenovia College        118

In [7]:
df['Grad.Rate']['Cazenovia College'] = 100

# Try removing various columns (features) from the dataset and examin if it improves/degrades your K-Means model performance, or it may have little impact.
# Report 10 cases where you removed one or more features and indicate how it impacted the model performance.

C:\Users\janic\AppData\Local\Temp\ipykernel_24760\3450590736.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Grad.Rate']['Cazenovia College'] = 100


In [8]:
df[df['Grad.Rate']>100] # data confirmation

Empty DataFrame
Columns: [Private, Apps, Accept, Enroll, Top10perc, Top25perc, F.Undergrad, P.Undergrad, Outstate, Room.Board, Books, Personal, PhD, Terminal, S.F.Ratio, perc.alumni, Expend, Grad.Rate]
Index: []

In [9]:
from sklearn.cluster import KMeans

In [10]:
kmeans = KMeans(n_clusters=2)

In [11]:
kmeans.fit(df.drop('Private', axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop('Private', axis=1))
df['Cluster_predict'] = Cluster_predict
df.head(5)

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 1.07191759e+04
  4.64347222e+03 5.95212963e+02 1.71420370e+03 8.63981481e+01
  9.13333333e+01 1.40277778e+01 2.00740741e+01 1.41705000e+04
  6.75925926e+01]
 [1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 1.03957085e+04
  4.31136472e+03 5.41982063e+02 1.28033632e+03 7.04424514e+01
  7.78251121e+01 1.40997010e+01 2.31748879e+01 8.93204634e+03
  6.50926756e+01]]


Private  Apps  Accept  Enroll  Top10perc  \
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  \
Abilene Christian University       18.1           12    7041         60   
Adelphi University                 12.2           16   10527         56   
Adrian College                     12.9           30    8735         54   
Agnes Scott College                 7.7           37   19016         59   
Alaska Pacific University          11.9            2   10922         15   

                              Cluster_predict  
Abilene Christian University                1  
Adelphi University                          1  
Adrian College                              1  
Agnes Scott College                         1  
Alaska Pacific University                   1

In [12]:
def convert_to_binary(cluster):
    if cluster == 'Yes':
        return 1
    else:
        return 0


In [13]:
df['Cluster_actual'] = df['Private'].apply(convert_to_binary)

In [14]:
df.head(5)

Private  Apps  Accept  Enroll  Top10perc  \
Abilene Christian University     Yes  1660    1232     721         23   
Adelphi University               Yes  2186    1924     512         16   
Adrian College                   Yes  1428    1097     336         22   
Agnes Scott College              Yes   417     349     137         60   
Alaska Pacific University        Yes   193     146      55         16   

                              Top25perc  F.Undergrad  P.Undergrad  Outstate  \
Abilene Christian University         52         2885          537      7440   
Adelphi University                   29         2683         1227     12280   
Adrian College                       50         1036           99     11250   
Agnes Scott College                  89          510           63     12960   
Alaska Pacific University            44          249          869      7560   

                              Room.Board  Books  Personal  PhD  Terminal  \
Abilene Christian University        3300    450      2200   70        78   
Adelphi University                  6450    750      1500   29        30   
Adrian College                      3750    400      1165   53        66   
Agnes Scott College                 5450    450       875   92        97   
Alaska Pacific University           4120    800      1500   76        72   

                              S.F.Ratio  perc.alumni  Expend  Grad.Rate  \
Abilene Christian University       18.1           12    7041         60   
Adelphi University                 12.2           16   10527         56   
Adrian College                     12.9           30    8735         54   
Agnes Scott College                 7.7           37   19016         59   
Alaska Pacific University          11.9            2   10922         15   

                              Cluster_predict  Cluster_actual  
Abilene Christian University                1               1  
Adelphi University                          1               1  
Adrian College                              1               1  
Agnes Scott College                         1               1  
Alaska Pacific University                   1               1

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
print(confusion_matrix(df['Cluster_actual'], kmeans.labels_))

[[ 74 138]
 [ 34 531]]


## Case 1 - Books feature removed

In [17]:
#store all results in a new table
results = df[['Cluster_predict', 'Cluster_actual' ]].copy()

df = df.drop('Cluster_predict', axis=1)
df = df.drop('Cluster_actual', axis=1)

In [18]:
kmeans.fit(df.drop(['Private', 'Books'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'Books'], axis=1))
results['case1'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 1.03957085e+04
  4.31136472e+03 1.28033632e+03 7.04424514e+01 7.78251121e+01
  1.40997010e+01 2.31748879e+01 8.93204634e+03 6.50926756e+01]
 [1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 1.07191759e+04
  4.64347222e+03 1.71420370e+03 8.63981481e+01 9.13333333e+01
  1.40277778e+01 2.00740741e+01 1.41705000e+04 6.75925926e+01]]


## Case 2 - F. Undergrad feature Removed

In [19]:
kmeans.fit(df.drop(['Private', 'F.Undergrad'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'F.Undergrad'], axis=1))
results['case2'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[2.27269968e+03 1.64662987e+03 6.85485390e+02 2.23750000e+01
  5.06347403e+01 8.74996753e+02 9.04055357e+03 4.10016721e+03
  5.42170455e+02 1.39076623e+03 6.89042208e+01 7.62678571e+01
  1.49392857e+01 2.04707792e+01 7.80917695e+03 6.21509740e+01]
 [5.79062112e+03 3.44277640e+03 1.14149068e+03 4.73913043e+01
  7.55465839e+01 7.79931677e+02 1.57976335e+04 5.34220497e+03
  5.76968944e+02 1.14886335e+03 8.70310559e+01 9.28447205e+01
  1.08391304e+01 3.14409938e+01 1.67422360e+04 7.80248447e+01]]


## Case 3: Grad. Rate Removed 

In [20]:
kmeans.fit(df.drop(['Private', 'Grad.Rate'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'Grad.Rate'], axis=1))
results['case3'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 1.03957085e+04
  4.31136472e+03 5.41982063e+02 1.28033632e+03 7.04424514e+01
  7.78251121e+01 1.40997010e+01 2.31748879e+01 8.93204634e+03]
 [1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 1.07191759e+04
  4.64347222e+03 5.95212963e+02 1.71420370e+03 8.63981481e+01
  9.13333333e+01 1.40277778e+01 2.00740741e+01 1.41705000e+04]]


## Case 4: Room.Board and perc.alum removed

In [21]:
kmeans.fit(df.drop(['Private', 'Room.Board', 'perc.alumni'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'Room.Board', 'perc.alumni'], axis=1))
results['case4'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 1.03957085e+04
  5.41982063e+02 1.28033632e+03 7.04424514e+01 7.78251121e+01
  1.40997010e+01 8.93204634e+03 6.50926756e+01]
 [1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 1.07191759e+04
  5.95212963e+02 1.71420370e+03 8.63981481e+01 9.13333333e+01
  1.40277778e+01 1.41705000e+04 6.75925926e+01]]


## Case 5:Top10perc & Top25perc removed

In [22]:
kmeans.fit(df.drop(['Private', 'Top10perc', 'Top25perc'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'Top10perc', 'Top25perc'], axis=1))
results['case5'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.03631389e+04 6.55089815e+03 2.56972222e+03 1.30619352e+04
  2.46486111e+03 1.07191759e+04 4.64347222e+03 5.95212963e+02
  1.71420370e+03 8.63981481e+01 9.13333333e+01 1.40277778e+01
  2.00740741e+01 1.41705000e+04 6.75925926e+01]
 [1.81323468e+03 1.28716592e+03 4.91044843e+02 2.18854858e+03
  5.95458894e+02 1.03957085e+04 4.31136472e+03 5.41982063e+02
  1.28033632e+03 7.04424514e+01 7.78251121e+01 1.40997010e+01
  2.31748879e+01 8.93204634e+03 6.50926756e+01]]


## Case 6: Accept & Enroll removed

In [23]:
kmeans.fit(df.drop(['Private', 'Accept', 'Enroll'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private', 'Accept', 'Enroll'], axis=1))
results['case6'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.05324369e+04 4.22621359e+01 7.04854369e+01 1.32799515e+04
  2.51251456e+03 1.07732233e+04 4.65533010e+03 5.97932039e+02
  1.73386408e+03 8.66796117e+01 9.14660194e+01 1.39233010e+01
  2.01456311e+01 1.44687282e+04 6.73786408e+01]
 [1.85078932e+03 2.53115727e+01 5.35519288e+01 2.23589466e+03
  6.02044510e+02 1.03898487e+04 4.31201632e+03 5.41961424e+02
  1.28055045e+03 7.05178042e+01 7.79050445e+01 1.41151335e+01
  2.31409496e+01 8.92533234e+03 6.51439169e+01]]


## Case 7: Apps, Accecpt & Enroll removed

In [24]:
kmeans.fit(df.drop(['Private','Apps', 'Accept', 'Enroll'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private','Apps', 'Accept', 'Enroll'], axis=1))
results['case7'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[2.25112179e+01 5.09246795e+01 3.91677885e+03 1.00006410e+03
  8.93987019e+03 4.10297115e+03 5.42666667e+02 1.41851122e+03
  6.93076923e+01 7.65480769e+01 1.49653846e+01 1.99278846e+01
  7.87163622e+03 6.21201923e+01]
 [4.81437908e+01 7.56666667e+01 2.81541176e+03 2.64882353e+02
  1.65615752e+04 5.39571242e+03 5.76764706e+02 1.02305882e+03
  8.63333333e+01 9.25686275e+01 1.05183007e+01 3.42287582e+01
  1.69545882e+04 7.89803922e+01]]


## Case 8: Books, Room.Board & perc.alumni removed

In [25]:
kmeans.fit(df.drop(['Private','Books','Room.Board','perc.alumni'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private','Books','Room.Board','perc.alumni'], axis=1))
results['case8'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 1.03957085e+04
  1.28033632e+03 7.04424514e+01 7.78251121e+01 1.40997010e+01
  8.93204634e+03 6.50926756e+01]
 [1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 1.07191759e+04
  1.71420370e+03 8.63981481e+01 9.13333333e+01 1.40277778e+01
  1.41705000e+04 6.75925926e+01]]


## Case 9: Outstate, Room.Board, Books, Personal & Perc.alumni removed

In [26]:
kmeans.fit(df.drop(['Private','Outstate','Room.Board','Books','Personal','perc.alumni'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private','Outstate','Room.Board','Books','Personal','perc.alumni'], axis=1))
results['case9'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[1.81323468e+03 1.28716592e+03 4.91044843e+02 2.53094170e+01
  5.34708520e+01 2.18854858e+03 5.95458894e+02 7.04424514e+01
  7.78251121e+01 1.40997010e+01 8.93204634e+03 6.50926756e+01]
 [1.03631389e+04 6.55089815e+03 2.56972222e+03 4.14907407e+01
  7.02037037e+01 1.30619352e+04 2.46486111e+03 8.63981481e+01
  9.13333333e+01 1.40277778e+01 1.41705000e+04 6.75925926e+01]]


## Case 10: Apps, Accept, Enroll, Personal, & perc.alumni removed

In [27]:
kmeans.fit(df.drop(['Private','Apps','Accept','Enroll','Personal','perc.alumni'], axis=1))
print(kmeans.cluster_centers_) #returns the values of the centeriods
Cluster_predict = kmeans.predict(df.drop(['Private','Apps','Accept','Enroll','Personal','perc.alumni'], axis=1))
results['case10'] = Cluster_predict

c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\janic\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


[[2.24768000e+01 5.08752000e+01 3.91135200e+03 9.98980800e+02
  8.94353440e+03 4.10703520e+03 5.45542400e+02 6.92096000e+01
  7.65184000e+01 1.49523200e+01 7.87988160e+03 6.20960000e+01]
 [4.84539474e+01 7.60328947e+01 2.83048026e+03 2.64500000e+02
  1.65966513e+04 5.38750658e+03 5.65164474e+02 8.68486842e+01
  9.27960526e+01 1.05427632e+01 1.69804408e+04 7.91907895e+01]]


In [28]:
print("actual - predicted \n", confusion_matrix(results['Cluster_actual'], results['Cluster_predict']))
print("Case 1: actual - predicted with no books \n", confusion_matrix(results['Cluster_actual'], results['case1']))
print("Case 2: actual - predicted with no F. Undergrad \n", confusion_matrix(results['Cluster_actual'], results['case2']))
print("Case 3: actual - predicted with no Grad.Rate \n", confusion_matrix(results['Cluster_actual'], results['case3']))
print("Case 4: actual - predicted with no Room.Board & perc.alumni \n", confusion_matrix(results['Cluster_actual'], results['case4']))
print("Case 5: actual - predicted with no Top10perc & Top25perc \n", confusion_matrix(results['Cluster_actual'], results['case5']))
print("Case 6: actual - predicted with no Accept & Enroll \n", confusion_matrix(results['Cluster_actual'], results['case6']))
print("Case 7: actual - predicted with no Apps, Accecpt & Enroll \n", confusion_matrix(results['Cluster_actual'], results['case7']))
print("Case 8: actual - predicted with no Books, Room.Board & perc.alumni \n", confusion_matrix(results['Cluster_actual'], results['case8']))
print("Case 9: actual - predicted with no Outstate, Room.Board, Books, Personal & Perc.alumni \n", confusion_matrix(results['Cluster_actual'], results['case9']))
print("Case 10: actual - predicted with no Apps, Accept, Enroll, Personal, & perc.alumni \n", confusion_matrix(results['Cluster_actual'], results['case10']))


actual - predicted 
 [[ 74 138]
 [ 34 531]]
Case 1: actual - predicted with no books 
 [[138  74]
 [531  34]]
Case 2: actual - predicted with no F. Undergrad 
 [[189  23]
 [427 138]]
Case 3: actual - predicted with no Grad.Rate 
 [[138  74]
 [531  34]]
Case 4: actual - predicted with no Room.Board & perc.alumni 
 [[138  74]
 [531  34]]
Case 5: actual - predicted with no Top10perc & Top25perc 
 [[ 74 138]
 [ 34 531]]
Case 6: actual - predicted with no Accept & Enroll 
 [[ 72 140]
 [ 31 534]]
Case 7: actual - predicted with no Apps, Accecpt & Enroll 
 [[209   3]
 [415 150]]
Case 8: actual - predicted with no Books, Room.Board & perc.alumni 
 [[138  74]
 [531  34]]
Case 9: actual - predicted with no Outstate, Room.Board, Books, Personal & Perc.alumni 
 [[138  74]
 [531  34]]
Case 10: actual - predicted with no Apps, Accept, Enroll, Personal, & perc.alumni 
 [[209   3]
 [416 149]]


Conclusion:
Going through the 10 cases where we remove one or more features and comparing their confusion matrixes, we can observe that the number of features removed does not always signify that there will be a big impact to the actual result. Rather, the impact lies whether the removed feature bears a heavy relevance or importance to the table or not.