<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 7</p>

In [1]:
# you can download the original Kyphosis dataset from kaggle at https://www.kaggle.com/abbasit/kyphosis-dataset?select=kyphosis.csv

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
Kyphosis_df = pd.read_csv('kyphosis.csv')
Kyphosis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64 
 2   Number    81 non-null     int64 
 3   Start     81 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 2.7+ KB


In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = Kyphosis_df.drop('Kyphosis',axis=1)
y = Kyphosis_df['Kyphosis']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [6]:
from sklearn.tree import DecisionTreeClassifier, plot_tree

In [7]:
# selecting the right "parameters/hyperparameters of ML models can significantly affect their performacnce".
# let's begin exploring those parameters more for a DT model.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

'''
DecisionTreeClassifier(
    criterion='gini',
    splitter='best',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=None,
    max_leaf_nodes=None,
    min_impurity_decrease=0.0,
    min_impurity_split=None,
    class_weight=None,
    presort=False,
)
'''
# Let's consider these three parameters: criterion, splitter, min_samples_split
    # for parameters consider two cases 'gini' and 'entropy'
    # for splitter consider two cases 'best' and 'random'
    # for min_samples_split consider two cases 2 and 5
    # explain and dicuss your findings

"\nDecisionTreeClassifier(\n    criterion='gini',\n    splitter='best',\n    max_depth=None,\n    min_samples_split=2,\n    min_samples_leaf=1,\n    min_weight_fraction_leaf=0.0,\n    max_features=None,\n    random_state=None,\n    max_leaf_nodes=None,\n    min_impurity_decrease=0.0,\n    min_impurity_split=None,\n    class_weight=None,\n    presort=False,\n)\n"

In [8]:
for i in (["gini", "entropy"]):
    for j in (["best", "random"]):
        for k in([2, 5]):
            dtree_gini_0 = DecisionTreeClassifier(
                criterion=i,
                splitter=j,
                min_samples_split=k
                )
            dtree_gini_0.fit(X_train,y_train)
            DTC_predictions_0 = dtree_gini_0.predict(X_test)

            score = accuracy_score(y_test, DTC_predictions_0) 
            print(f"DecisionTreeClassifier using criterion='{i}', splitter='{j}' and min_samples_split={k}, with accuracy_score: {score}")
            print(confusion_matrix(y_test,DTC_predictions_0))
            


DecisionTreeClassifier using criterion='gini', splitter='best' and min_samples_split=2, with accuracy_score: 0.84
[[20  3]
 [ 1  1]]
DecisionTreeClassifier using criterion='gini', splitter='best' and min_samples_split=5, with accuracy_score: 0.88
[[21  2]
 [ 1  1]]
DecisionTreeClassifier using criterion='gini', splitter='random' and min_samples_split=2, with accuracy_score: 0.8
[[19  4]
 [ 1  1]]
DecisionTreeClassifier using criterion='gini', splitter='random' and min_samples_split=5, with accuracy_score: 0.88
[[21  2]
 [ 1  1]]
DecisionTreeClassifier using criterion='entropy', splitter='best' and min_samples_split=2, with accuracy_score: 0.84
[[20  3]
 [ 1  1]]
DecisionTreeClassifier using criterion='entropy', splitter='best' and min_samples_split=5, with accuracy_score: 0.88
[[21  2]
 [ 1  1]]
DecisionTreeClassifier using criterion='entropy', splitter='random' and min_samples_split=2, with accuracy_score: 0.96
[[23  0]
 [ 1  1]]
DecisionTreeClassifier using criterion='entropy', split

### Conclusion
## Best vs random 

In terms of confusion matrix, the best criterion results in fewer errors and a higher overall accuracy. However, it may be more prone to overfitting and less robust to noisy data. The random criterion results in lower overall accuracy.

## Gini vs Entropy

In terms of confusion matrix, both Gini criterion and entropy criterion may lead to similar results, but Gini criterion is computationally less expensive and considered to be more robust to noisy data.

## Min_Sample_Split


When min_samples_split is low, the tree will be grown more, which means it will have more splits and more complex.

When min_samples_split is high, the tree will be grown less, which means it will have fewer splits and less complex.

In this case, we could observe that when we changed min_sample_split from 2 to 5, it’s giving us better accuracy
