<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 9</p>

In [20]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
import sklearn.model_selection as sci
from sklearn.metrics import  accuracy_score

In [21]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length

print("iris dataset",iris.data[:,:-1])
X = iris.data[:, -1] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y)

iris dataset [[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]
 [5.4 3.9 1.7]
 [4.6 3.4 1.4]
 [5.  3.4 1.5]
 [4.4 2.9 1.4]
 [4.9 3.1 1.5]
 [5.4 3.7 1.5]
 [4.8 3.4 1.6]
 [4.8 3.  1.4]
 [4.3 3.  1.1]
 [5.8 4.  1.2]
 [5.7 4.4 1.5]
 [5.4 3.9 1.3]
 [5.1 3.5 1.4]
 [5.7 3.8 1.7]
 [5.1 3.8 1.5]
 [5.4 3.4 1.7]
 [5.1 3.7 1.5]
 [4.6 3.6 1. ]
 [5.1 3.3 1.7]
 [4.8 3.4 1.9]
 [5.  3.  1.6]
 [5.  3.4 1.6]
 [5.2 3.5 1.5]
 [5.2 3.4 1.4]
 [4.7 3.2 1.6]
 [4.8 3.1 1.6]
 [5.4 3.4 1.5]
 [5.2 4.1 1.5]
 [5.5 4.2 1.4]
 [4.9 3.1 1.5]
 [5.  3.2 1.2]
 [5.5 3.5 1.3]
 [4.9 3.6 1.4]
 [4.4 3.  1.3]
 [5.1 3.4 1.5]
 [5.  3.5 1.3]
 [4.5 2.3 1.3]
 [4.4 3.2 1.3]
 [5.  3.5 1.6]
 [5.1 3.8 1.9]
 [4.8 3.  1.4]
 [5.1 3.8 1.6]
 [4.6 3.2 1.4]
 [5.3 3.7 1.5]
 [5.  3.3 1.4]
 [7.  3.2 4.7]
 [6.4 3.2 4.5]
 [6.9 3.1 4.9]
 [5.5 2.3 4. ]
 [6.5 2.8 4.6]
 [5.7 2.8 4.5]
 [6.3 3.3 4.7]
 [4.9 2.4 3.3]
 [6.6 2.9 4.6]
 [5.2 2.7 3.9]
 [5.  2.  3.5]
 [5.9 3.  4.2]
 [6.  2.2 4. ]
 [6.1 2.9 4.7]
 [5.6 2.9 3.6]
 [6.7 3.1 4.

In [22]:
X_train, X_test, y_train, y_test = sci.train_test_split(X, y, test_size=0.3, random_state=1)

In [23]:
X_train= X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

SVM


In [24]:
clf = svm.SVC()

# Train the model on the training data
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
# Test the model on the testing data
score = clf.score(X_test, y_test)
print("Score:", score)



Score: 0.9555555555555556


In [25]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models

GridSearchCV

In [28]:
param_grid = {'C': [1,5, 20,100,500], 'gamma': [.001, .01, .1,1], 'kernel': ['linear', 'rbf']}


svc = svm.SVC()


grid_search = GridSearchCV(svc, param_grid,scoring='accuracy')


grid_search.fit(X_train, y_train)
y_pred=grid_search.predict(X_test)


print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)


Best parameters: {'C': 5, 'gamma': 0.001, 'kernel': 'linear'}
Best score: 0.9714285714285715


SVM with default parameters  give a score of .955 Whereas GridSearch with best parameters(C:5,gamma:.01,kernel:lenear) give a score of .972