<p style="font-family: Arial; font-size:3em;color:black;"> Session 4 - Lab Exercise 8</p>

We will use the titanic dataset from Kaggle (https://www.kaggle.com/). This is a well-known dataset and we will use it for classification- if the passenger survived or passed away.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
training_DF = pd.read_csv('titanic_dataset_GBC.csv')

In [4]:
training_DF['Age'].fillna(training_DF['Age'].mean(), inplace=True)

In [5]:
training_DF.drop('Cabin',axis=1,inplace=True)

In [6]:
training_DF.dropna(inplace=True)

In [7]:
sex = pd.get_dummies(training_DF['Sex'])
embark = pd.get_dummies(training_DF['Embarked'])

In [8]:
training_DF.drop(['Sex','Embarked','Name','Ticket'],axis=1,inplace=True)

In [9]:
training_DF = pd.concat([training_DF,sex,embark],axis=1)

In [10]:
training_DF.drop(['female','C'],axis=1,inplace=True)

In [11]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(training_DF.drop('Survived',axis=1), 
                                                    training_DF['Survived'], test_size=0.30, 
                                                    random_state=101)

In [35]:
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)

In [ ]:
# Let's form SGD models with variation in parameters loss and alpha
    # loss: 'hinge', 'log', and 'modified_huber'
    # alpha: 0.0001 and 0.001
    # explain and dicuss your findings

In [55]:
# let's explore SGDClassifier parameters

# loss: hinge, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)


sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
hinge_alpha1 = confusion_matrix(y_test,sdg_prediction)
print(hinge_alpha1)

[[ 15 148]
 [  9  95]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [56]:
# loss: log, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='log_loss',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
log_alpha1 = confusion_matrix(y_test,sdg_prediction)
print(log_alpha1)

[[ 54 109]
 [ 38  66]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [57]:
# loss: modified_huber, alpha: 0.0001
sdg_model = SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.0001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
huber_alpha1 = confusion_matrix(y_test,sdg_prediction)
print(hinge_alpha1)

[[ 15 148]
 [  9  95]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [58]:
# loss: hinge, alpha: 0.001
sdg_model = SGDClassifier(
    loss='hinge',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
hinge_alpha2 = confusion_matrix(y_test,sdg_prediction)
print(hinge_alpha2)

[[ 40 123]
 [ 25  79]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [59]:
# loss: log, alpha: 0.001
sdg_model = SGDClassifier(
    loss='log_loss',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
log_alpha2 = confusion_matrix(y_test,sdg_prediction)
print(log_alpha2)

[[115  48]
 [ 54  50]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [60]:
# loss: modified_huber, alpha: 0.001
sdg_model = SGDClassifier(
    loss='modified_huber',
    penalty='l2',
    alpha=0.001,
    l1_ratio=0.15,
    fit_intercept=True,
    max_iter=1000,
    tol=0.001,
    shuffle=True,
    verbose=0,
    epsilon=0.1,
    n_jobs=None,
    random_state=101,
    learning_rate='optimal',
    eta0=0.0,
    power_t=0.5,
    early_stopping=False,
    validation_fraction=0.1,
    n_iter_no_change=5,
    class_weight=None,
    warm_start=False,
    average=False,
)

sdg_model.fit(X_train, y_train)

sdg_prediction = sdg_model.predict(X_test)

from sklearn.metrics import confusion_matrix
huber_alpha2 = confusion_matrix(y_test,sdg_prediction)
print(huber_alpha2)

[[ 41 122]
 [ 26  78]]


M:\GBC\App. Math 1\app_math1-venv\Lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but SGDClassifier was fitted without feature names
  warnings.warn(


In [61]:
# Summary
print("loss: hinge, alpha: 0.0001\n", hinge_alpha1)
print("loss: log, alpha: 0.0001\n", log_alpha1)
print("loss: modified_huber, alpha: 0.0001\n", huber_alpha2)
print("loss: hinge, alpha: 0.001\n", hinge_alpha2)
print("loss: log, alpha: 0.001\n", log_alpha2)
print("loss: modified_huber, alpha: 0.001\n", huber_alpha2)

loss: hinge, alpha: 0.0001
 [[ 15 148]
 [  9  95]]
loss: log, alpha: 0.0001
 [[ 54 109]
 [ 38  66]]
loss: modified_huber, alpha: 0.0001
 [[ 41 122]
 [ 26  78]]
loss: hinge, alpha: 0.001
 [[ 40 123]
 [ 25  79]]
loss: log, alpha: 0.001
 [[115  48]
 [ 54  50]]
loss: modified_huber, alpha: 0.001
 [[ 41 122]
 [ 26  78]]


Hinge loss is used for training linear Support Vector Machines (SVMs) for classification tasks. It is a loss function that is used for "maximum-margin" classification, where the goal is to separate the classes by a large margin.

Log loss, also known as cross-entropy loss, is commonly used in classification tasks with a probability output, such as logistic regression. It measures the performance of a classification model whose output is a probability value between 0 and 1.

Modified Huber loss is a combination of Mean Squared Error and Mean Absolute Error. It is used for robust regression and classification. It is less sensitive to outliers than the Mean Squared Error (MSE) loss function, but unlike the Mean Absolute Error (MAE) loss function, it does not become too large for large errors.

The `alpha` parameter controls the strength of the regularization term, with a higher value of `alpha` corresponding to a stronger regularization. The regularization term added to the loss function is in the form of a constant multiplied by the sum of the absolute values of the weights (L1 regularization) or the sum of the squares of the weights (L2 regularization).

The SGDClassifier uses L2 regularization by default, but you can change it to L1 regularization by setting the penalty parameter to "l1".